name: Mise setup
description: Common steps before running mise tasks
runs:
  using: composite
  steps:
    - uses: jdx/mise-action@v2
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
