// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/luckymaks/bm_backend/backend/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockModelClient is an autogenerated mock type for the ModelClient type
type MockModelClient struct {
	mock.Mock
}

type MockModelClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModelClient) EXPECT() *MockModelClient_Expecter {
	return &MockModelClient_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function with given fields: ctx, input
func (_m *MockModelClient) CreateItem(ctx context.Context, input model.CreateItemInput) (*model.CreateItemOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *model.CreateItemOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateItemInput) (*model.CreateItemOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.CreateItemInput) *model.CreateItemOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CreateItemOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.CreateItemInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelClient_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockModelClient_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.CreateItemInput
func (_e *MockModelClient_Expecter) CreateItem(ctx interface{}, input interface{}) *MockModelClient_CreateItem_Call {
	return &MockModelClient_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, input)}
}

func (_c *MockModelClient_CreateItem_Call) Run(run func(ctx context.Context, input model.CreateItemInput)) *MockModelClient_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.CreateItemInput))
	})
	return _c
}

func (_c *MockModelClient_CreateItem_Call) Return(_a0 *model.CreateItemOutput, _a1 error) *MockModelClient_CreateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelClient_CreateItem_Call) RunAndReturn(run func(context.Context, model.CreateItemInput) (*model.CreateItemOutput, error)) *MockModelClient_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function with given fields: ctx, input
func (_m *MockModelClient) GetItem(ctx context.Context, input model.GetItemInput) (*model.GetItemOutput, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *model.GetItemOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetItemInput) (*model.GetItemOutput, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetItemInput) *model.GetItemOutput); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GetItemOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetItemInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockModelClient_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockModelClient_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input model.GetItemInput
func (_e *MockModelClient_Expecter) GetItem(ctx interface{}, input interface{}) *MockModelClient_GetItem_Call {
	return &MockModelClient_GetItem_Call{Call: _e.mock.On("GetItem", ctx, input)}
}

func (_c *MockModelClient_GetItem_Call) Run(run func(ctx context.Context, input model.GetItemInput)) *MockModelClient_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GetItemInput))
	})
	return _c
}

func (_c *MockModelClient_GetItem_Call) Return(_a0 *model.GetItemOutput, _a1 error) *MockModelClient_GetItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockModelClient_GetItem_Call) RunAndReturn(run func(context.Context, model.GetItemInput) (*model.GetItemOutput, error)) *MockModelClient_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModelClient creates a new instance of MockModelClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModelClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModelClient {
	mock := &MockModelClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		mock.AssertExpectations(t)
	})

	return mock
}
