// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: bm/v1/api.proto

package bmv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_bm_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bm_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetHealthRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetHealthRequest_builder) Build() *GetHealthRequest {
	m0 := &GetHealthRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetHealthResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      *string                `protobuf:"bytes,1,opt,name=status"`
	xxx_hidden_Region      *string                `protobuf:"bytes,2,opt,name=region"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_bm_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bm_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *GetHealthResponse) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *GetHealthResponse) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *GetHealthResponse) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *GetHealthResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetHealthResponse) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetHealthResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = nil
}

func (x *GetHealthResponse) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Region = nil
}

type GetHealthResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// status of the health response
	Status *string
	// region
	Region *string
}

func (b0 GetHealthResponse_builder) Build() *GetHealthResponse {
	m0 := &GetHealthResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = b.Status
	}
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Region = b.Region
	}
	return m0
}

type CreateItemRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Data        *string                `protobuf:"bytes,2,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_bm_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bm_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateItemRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CreateItemRequest) GetData() string {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
		return ""
	}
	return ""
}

func (x *CreateItemRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateItemRequest) SetData(v string) {
	x.xxx_hidden_Data = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CreateItemRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateItemRequest) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateItemRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CreateItemRequest) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

type CreateItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// id of an item
	Id *string
	// data of an item
	Data *string
}

func (b0 CreateItemRequest_builder) Build() *CreateItemRequest {
	m0 := &CreateItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type CreateItemResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_bm_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bm_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateItemResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CreateItemResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *CreateItemResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateItemResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type CreateItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// id of an item
	Id *string
}

func (b0 CreateItemResponse_builder) Build() *CreateItemResponse {
	m0 := &CreateItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type GetItemRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_bm_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bm_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetItemRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetItemRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetItemRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetItemRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// id of an item
	Id *string
}

func (b0 GetItemRequest_builder) Build() *GetItemRequest {
	m0 := &GetItemRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type GetItemResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Data        *string                `protobuf:"bytes,2,opt,name=data"`
	xxx_hidden_CreatedAt   *string                `protobuf:"bytes,3,opt,name=created_at,json=createdAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_bm_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bm_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetItemResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetItemResponse) GetData() string {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
		return ""
	}
	return ""
}

func (x *GetItemResponse) GetCreatedAt() string {
	if x != nil {
		if x.xxx_hidden_CreatedAt != nil {
			return *x.xxx_hidden_CreatedAt
		}
		return ""
	}
	return ""
}

func (x *GetItemResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *GetItemResponse) SetData(v string) {
	x.xxx_hidden_Data = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *GetItemResponse) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *GetItemResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetItemResponse) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetItemResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetItemResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *GetItemResponse) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Data = nil
}

func (x *GetItemResponse) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CreatedAt = nil
}

type GetItemResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// id of an item
	Id *string
	// data of an item
	Data *string
	// date when item was created
	CreatedAt *string
}

func (b0 GetItemResponse_builder) Build() *GetItemResponse {
	m0 := &GetItemResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = b.Id
	}
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Data = b.Data
	}
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_CreatedAt = b.CreatedAt
	}
	return m0
}

var File_bm_v1_api_proto protoreflect.FileDescriptor

const file_bm_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x0fbm/v1/api.proto\x12\x05bm.v1\x1a\x1bbuf/validate/validate.proto\"\x12\n" +
	"\x10GetHealthRequest\"K\n" +
	"\x11GetHealthResponse\x12\x1e\n" +
	"\x06status\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06status\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"G\n" +
	"\x11CreateItemRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\x12\x1a\n" +
	"\x04data\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04data\",\n" +
	"\x12CreateItemResponse\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\"(\n" +
	"\x0eGetItemRequest\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\"l\n" +
	"\x0fGetItemResponse\x12\x16\n" +
	"\x02id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x02id\x12\x1a\n" +
	"\x04data\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04data\x12%\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt2\xc9\x01\n" +
	"\n" +
	"ApiService\x12>\n" +
	"\tGetHealth\x12\x17.bm.v1.GetHealthRequest\x1a\x18.bm.v1.GetHealthResponse\x12A\n" +
	"\n" +
	"CreateItem\x12\x18.bm.v1.CreateItemRequest\x1a\x19.bm.v1.CreateItemResponse\x128\n" +
	"\aGetItem\x12\x15.bm.v1.GetItemRequest\x1a\x16.bm.v1.GetItemResponseB\x84\x01\n" +
	"\tcom.bm.v1B\bApiProtoP\x01Z8github.com/luckymaks/bm_backend/backend/proto/bm/v1;bmv1\xa2\x02\x03BXX\xaa\x02\x05Bm.V1\xca\x02\x05Bm\\V1\xe2\x02\x11Bm\\V1\\GPBMetadata\xea\x02\x06Bm::V1b\beditionsp\xe8\a"

var file_bm_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bm_v1_api_proto_goTypes = []any{
	(*GetHealthRequest)(nil),   // 0: bm.v1.GetHealthRequest
	(*GetHealthResponse)(nil),  // 1: bm.v1.GetHealthResponse
	(*CreateItemRequest)(nil),  // 2: bm.v1.CreateItemRequest
	(*CreateItemResponse)(nil), // 3: bm.v1.CreateItemResponse
	(*GetItemRequest)(nil),     // 4: bm.v1.GetItemRequest
	(*GetItemResponse)(nil),    // 5: bm.v1.GetItemResponse
}
var file_bm_v1_api_proto_depIdxs = []int32{
	0, // 0: bm.v1.ApiService.GetHealth:input_type -> bm.v1.GetHealthRequest
	2, // 1: bm.v1.ApiService.CreateItem:input_type -> bm.v1.CreateItemRequest
	4, // 2: bm.v1.ApiService.GetItem:input_type -> bm.v1.GetItemRequest
	1, // 3: bm.v1.ApiService.GetHealth:output_type -> bm.v1.GetHealthResponse
	3, // 4: bm.v1.ApiService.CreateItem:output_type -> bm.v1.CreateItemResponse
	5, // 5: bm.v1.ApiService.GetItem:output_type -> bm.v1.GetItemResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bm_v1_api_proto_init() }
func file_bm_v1_api_proto_init() {
	if File_bm_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bm_v1_api_proto_rawDesc), len(file_bm_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bm_v1_api_proto_goTypes,
		DependencyIndexes: file_bm_v1_api_proto_depIdxs,
		MessageInfos:      file_bm_v1_api_proto_msgTypes,
	}.Build()
	File_bm_v1_api_proto = out.File
	file_bm_v1_api_proto_goTypes = nil
	file_bm_v1_api_proto_depIdxs = nil
}
